version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper:zookeeper
  kafka-manager:
    image: dockerkafka/kafka-manager
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
      - "9000:9000"
    links:
      - zookeeper:zookeeper
      - kafka:kafka
  grafana_graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    links:
      - zookeeper:zookeeper
      - kafka:kafka
      - logstash:logstash
  logstash:
    build: .
    environment:
     ORDERS_KAFKA_HOST: kafka
     SPLIT_KAFKA_HOST: kafka
     GRPHITE: graphite
    links:
      - zookeeper:zookeeper
      - kafka:kafka
    depends_on:
      - kafka
